somnio-software/flutter-firebase-starter

lib/screens/profile/edit_profile_screen.dart
lib/services/auth/google/googe_auth_service.dart
lib/services/remote_config/remote_config.dart
lib/utils/dialog.dart

Lint fixes

---

lib/screens/auth/login_screen.dart

Fixes the profile info loading issue by firing the UserBloc's UserLoaded event when LoginBloc's LoginSuccess event occurs.

Fix: Fire UserLoaded event on loginSuccess

---

lib/services/auth/firebase_auth_service.dart

Fixes the sign out navigation errors. 
These were caused by having every sign out methods called regardless of the sign in method.
So in order to fix this, FB-78 had to be fixed.
Also, as a consequence of this fix, FB-88 was also fixed.

Fix: Sign out navigation errors

---

lib/bloc/employees/employees_bloc.dart
lib/bloc/employees/employees_state.dart
lib/models/employee.dart
lib/screens/team/team_screen.dart
test/bloc/employees/employees_bloc_test.dart
test/widget/employees/employees_widget_test.dart

Refactors employees bloc and updates tests.

Employees bloc refactor

---

lib/bloc/forgot_password/forgot_password_bloc.dart
lib/bloc/forgot_password/forgot_password_event.dart
lib/bloc/forgot_password/forgot_password_state.dart
lib/screens/auth/forgot_password_screen.dart

ForgotPasswordBloc refactor

---

lib/bloc/edit_profile/edit_profile_bloc.dart
lib/bloc/edit_profile/edit_profile_event.dart
lib/bloc/edit_profile/edit_profile_state.dart
lib/screens/profile/edit_profile_screen.dart
test/bloc/user/edit_profile_bloc_test.dart

Refactors edit profile bloc and updates tests.

Edit profile bloc refactor

---

lib/bloc/init_app/init_app_bloc.dart
lib/bloc/init_app/init_app_event.dart
lib/bloc/init_app/init_app_state.dart
lib/screens/init_app.dart

InitAppBloc refactor

---

lib/bloc/login/login_bloc.dart
lib/bloc/login/login_event.dart
lib/bloc/login/login_state.dart
lib/screens/auth/login_screen.dart
lib/screens/init_app.dart
lib/screens/settings/settings_screen.dart

LoginBloc refactor

---

lib/bloc/account_creation/account_creation_bloc.dart
lib/bloc/user/user_bloc.dart
lib/bloc/user/user_event.dart
lib/bloc/user/user_state.dart
lib/screens/auth/create_account_screen.dart
lib/screens/profile/user_profile_screen.dart
lib/services/auth/firebase_auth_service.dart
test/bloc/user/user_bloc_test.dart

UserBloc refactor

---

lib/bloc/login/login_bloc.dart
test/bloc/login/login_bloc_test.dart
test/bloc/login/mocks/login_bloc_mocks.dart

Adds unit testing for LoginBloc

Unit testing for LoginBloc

---

lib/bloc/init_app/init_app_bloc.dart
test/bloc/initApp/init_app_bloc_test.dart
test/bloc/initApp/mocks/init_app_bloc_mocks.dart

Adds unit testing for InitAppBloc

Unit testing init app bloc

---

lib/bloc/account_creation/account_creation_bloc.dart
test/bloc/accountCreation/account_creation_bloc_test.dart
test/bloc/accountCreation/mocks/account_creation_bloc_mocks.dart

Adds unit testing for AccountCreationBloc

Unit testing for AccountCreationBloc

---

lib/bloc/account_creation/account_creation_bloc.dart
lib/bloc/edit_profile/edit_profile_bloc.dart
lib/bloc/employees/employees_bloc.dart
lib/bloc/forgot_password/forgot_password_bloc.dart
lib/bloc/init_app/init_app_bloc.dart
lib/bloc/login/login_bloc.dart
lib/bloc/user/user_bloc.dart
test/bloc/accountCreation/account_creation_bloc_test.dart
test/bloc/forgotPassword/forgot_password_bloc_test.dart
test/bloc/forgotPassword/mocks/forgot_password_bloc_mocks.dart
test/bloc/initApp/init_app_bloc_test.dart
test/bloc/login/login_bloc_test.dart

Adds unit testing for ForgotPasswordBloc

Unit testing for ForgotPasswordBloc

---

lib/bloc/edit_profile/edit_profile_bloc.dart
lib/bloc/edit_profile/edit_profile_event.dart
lib/bloc/edit_profile/edit_profile_state.dart
lib/widgets/auth/login_form.dart
lib/widgets/edit_profile/edit_profile_form.dart
test/bloc/user/edit_profile_bloc_test.dart

Adds validation logic to the edit profile button

Flutter form builder button

---

lib/forms/forms.dart
lib/forms/models/email.dart
lib/forms/models/first_name.dart
lib/forms/models/last_name.dart
lib/forms/models/models.dart
lib/forms/models/password.dart

This PR introduces models to use inside screens that contains a `Form`.

feature: add models to form inputs

---

lib/onboarding/onboarding.dart
lib/onboarding/view/onboarding_screen.dart
lib/onboarding/view/view.dart

This PR reestructures the Onboarding feature into the feature driven approach.

refactor: onboarding feature driven

---

lib/login/view/login_screen.dart
lib/main.dart

fix: login screen

---

lib/forgot_password/bloc/forgot_password_bloc.dart
lib/forgot_password/bloc/forgot_password_state.dart
lib/forgot_password/view/forgot_password_screen.dart

fix: forgot password

---

lib/forgot_password/bloc/forgot_password_bloc.dart
lib/forgot_password/bloc/forgot_password_state.dart
lib/forgot_password/view/forgot_password_screen.dart
lib/forgot_password/view/view.dart
test/forgot_password/bloc/forgot_password_bloc_test.dart
test/forgot_password/bloc/forgot_password_event_test.dart
test/forgot_password/bloc/forgot_password_state_test.dart
test/forgot_password/view/forgot_password_screen_test.dart

This PR introduces the test for the `ForgotPassword` feature

test: forgot password

---

lib/sign_up/bloc/sign_up_bloc.dart
lib/sign_up/bloc/sign_up_event.dart
lib/sign_up/bloc/sign_up_state.dart
test/sign_up/bloc/sign_up_bloc_test.dart
test/sign_up/bloc/sign_up_event_test.dart
test/sign_up/bloc/sign_up_state_test.dart
test/sign_up/view/sign_up_view_test.dart

This PR expands the tests of the `SignUp` feature

test: sign up

---

lib/login/bloc/login_bloc.dart
lib/login/bloc/login_state.dart
test/login/bloc/login_event_test.dart
test/login/bloc/login_state_test.dart
test/login/view/login_screen_view_test.dart

This PR adds more tests on the `Login` feature

test: login

---

lib/user/bloc/user_bloc.dart
lib/user/user.dart
test/user/bloc/user_bloc_event_test.dart
test/user/bloc/user_bloc_state_test.dart
test/user/bloc/user_bloc_test.dart

This PR introduces more tests to the `UserBloc`

test: user feature

---

test/models/employee/employee_test.dart
test/models/user/user_test.dart

This PR refactors the location of the `Employee` and `User` tests

refactor: models

---

lib/edit_profile/bloc/edit_profile_bloc.dart
lib/edit_profile/bloc/edit_profile_event.dart
lib/edit_profile/view/edit_profile_screen.dart
test/edit_profile/bloc/edit_profile_bloc_test.dart
test/edit_profile/bloc/edit_profile_event_test.dart
test/edit_profile/bloc/edit_profile_state_test.dart
test/edit_profile/view/edit_profile_screen_test.dart

This PR introduces tests to the `EditProfileEvent` and `EditProfileState` entities

test: edit profile bloc

---

lib/edit_profile/view/edit_profile_screen.dart
lib/home/view/home_screen.dart
lib/user_profile/view/user_info_section.dart
lib/user_profile/view/user_profile_image.dart
lib/user_profile/view/user_profile_screen.dart
lib/user_profile/view/view.dart
test/user_profile/bloc/user_profile_bloc_test.dart
test/user_profile/view/user_profile_screen_test.dart

This PR adds tests on the `UserProfile` screen

test: user profile

---

lib/services/auth/firebase_auth_service.dart
test/services/auth/firebase_auth_test.dart

This PR removes unnecessary assertions that were causing a failure

fix: edit profile error

---

test/edit_profile/bloc/edit_profile_bloc_test.dart
test/sign_up/bloc/sign_up_bloc_test.dart

This PR adds missing verify statements in some tests

fix: add verify in tests

---

lib/locator.dart
lib/services/auth/sign_in_services/apple/apple_credentials.dart
lib/services/auth/sign_in_services/apple/apple_sign_in_service.dart
lib/services/auth/sign_in_services/facebook/facebook_sign_in_service.dart
lib/services/auth/sign_in_services/google/google_sign_in_service.dart
test/services/auth/sign_in_services/apple_credentials_test.dart
test/services/auth/sign_in_services/apple_sign_in_service_test.dart
test/services/auth/sign_in_services/facebook_sign_in_service_test.dart
test/services/auth/sign_in_services/google_sign_in_service_test.dart

This PR add tests to the `SocialMediaServices`

test: social media services

---

lib/login/bloc/login_bloc.dart
test/login/bloc/login_bloc_test.dart

This PR introduces the ability to `login anonymously`

feat: login anonymously

---

lib/edit_profile/bloc/edit_profile_bloc.dart
lib/edit_profile/view/edit_profile_screen.dart

Added spinner (CircularProgressIndicator) when the user tap Edit Profile button

feat:edit profile spinner

---

lib/home/view/starter_bottom_navigation_bar.dart

This PR fixes the `BottomNavigationBar` color

feat: bottom navigation bar

---

lib/employees/view/employees_screen.dart
lib/home/view/home_screen.dart
lib/user_profile/view/user_info_section.dart
lib/user_profile/view/user_profile_screen.dart
lib/widgets/common/app_bar.dart
test/user_profile/view/user_profile_screen_test.dart

This PR removes the back arrow in the `HomeScreen`.

feat: remove back arrow from home screen

---

lib/app.dart
lib/app/bloc/app_bloc.dart
lib/app/bloc/app_event.dart
lib/app/bloc/app_state.dart
lib/app/view/determine_access_screen.dart
lib/login/bloc/login_bloc.dart
lib/login/bloc/login_event.dart
lib/models/user.dart
lib/onboarding/view/onboarding_screen.dart
lib/settings/view/settings_screen.dart
test/app/bloc/app_bloc_test.dart
test/app/bloc/app_event_test.dart
test/app/bloc/app_state_test.dart
test/login/bloc/login_bloc_test.dart
test/login/bloc/login_event_test.dart

This PR reassigns the responsibility to _logout_.
Now, this process is on charge of the `AppBloc`.

feat: app logout
